### ISSUE TITLE
window system 

### ISSUE THREAD

**Issue by HelloToGithub** [hyperjump-io/json-schema-validator#14]
> @hyperjump/json-pointer@0.9.2 postinstall E:\Project\code\ui\enterprise\node_modules\@hyperjump\json-pointer
> rm -rf dist

'rm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by jdesrosiers** [comment]
Translation ...

> 'rm' is not an internal or external command, nor is it a runnable program or batch file.

This is related to https://github.com/hyperjump-io/json-schema-validator/issues/13. It looks like I'm going to have to revisit this solution to find something windows compatible.

**Comment by HanojHanu** [comment]
Hi, @jdesrosiers

Worked for me. now pack size reduce.

Otherwise, just leave this postinstall script instead of doing here.

Add in README Doc follow steps to create postinstall script to reduce package, this helps for other people.

**Comment by jdesrosiers** [comment]
It should now work in Windows. Sorry it took so long to fix.

**Comment by HanojHanu** [comment]
Great Work.

Thanks, @jdesrosiers
