### ISSUE TITLE
Undeclared rimraf dependency used in post install script

### ISSUE THREAD

**Issue by jviotti** [hyperjump-io/json-schema-validator#16]
Looks like this package makes use of `rimraf` as a `postinstall` script (https://github.com/hyperjump-io/json-schema-validator/blob/main/package.json#L16), which might fail for some people if `rimraf` is not previously installed.

See https://github.com/sourcemeta/alterschema/issues/44.

That said, I see `rimraf` is being ran using `npx`, which is supposed to pull it on demand, right? Maybe that doesn't quite work on some cases? (it seems to work for me)

**Comment by jdesrosiers** [comment]
I see no reason why it shouldn't work and it works fine for me and others. I can't do anything without a reproducible example.

**Comment by jdesrosiers** [comment]
I figured out that the problem occurs when installing globally using sudo. Example: `sudo npm install -g @hyperjump/json-schema-bundle`

**Comment by jdesrosiers** [comment]
I just published a patch that should fix the problem.

**Comment by jviotti** [comment]
Awesome! Thanks a lot @jdesrosiers.
