### ISSUE TITLE
README / API section copy and pasted description

### ISSUE THREAD

**Issue by MikeRalphson** [hyperjump-io/json-schema-validator#5]
In the API section two methods have the same description (apart from the word "See"), which looks incorrect.

## API
* **validate**: (schema: SDoc, instance: any, outputFormat: OutputFormat = FLAG) => OutputUnit

    Validate an instance against a schema. The function is curried to allow
    compiling the schema once and applying it to multiple instances. See
* **setMetaOutputFormat**: (outputFormat: OutputFormat) => undefined

    Validate an instance against a schema. The function is curried to allow
    compiling the schema once and applying it to multiple instances.

**Comment by jdesrosiers** [comment]
Looks like my editor was sleeping on the job. Oh wait, that's me :facepalm:

**Comment by jdesrosiers** [comment]
Fixed.
