### ISSUE TITLE
Possible to expose option to configure http-cache?

### ISSUE THREAD

**Issue by DanKottke** [hyperjump-io/json-schema-validator#7]
Howdy. Attempting to use this validator in an AWS Lambda env causes issues with attempts to write to disk. I believe the cause is in json-schema-core's usage of the "make-fetch-happen" library, where it codes as follows:

`const fetch = makeFetchHappen.defaults({ cacheManager: "./http-cache" });`

It would be excellent if the local location of this cache (and the option to disable it completely) would be exposed as configurable quantities in your lib. Love it otherwise!

**Comment by jdesrosiers** [comment]
Now that I think about it, I'm pretty sure I don't need that feature at all any more. It's a remnant of an early architecture that ended up changing. I'm looking into it. Thanks.

**Comment by jdesrosiers** [comment]
I went ahead and just removed it altogether. It wasn't serving any useful purpose any more. The only change was in the json-schema-core package, so you'll need to update with `--depth 1` to get the changes.
